### ISSUE TITLE
the training crashes because of the raytask 

### ISSUE THREAD

**Issue by Jeffrey28** [ZhongxiaYan/mixed_autonomy_intersections#8]
the config yaml is：
```
av_frac: 0.5
device: cpu
directions: 4way
n_cols: 1
n_rollouts_per_step: 256
n_rows: 1
n_workers: 16
worker_kwargs:
- flow_rate_h: 700
  flow_rate_v: 700
- flow_rate_h: 850
  flow_rate_v: 850
- flow_rate_h: 850
  flow_rate_v: 700
- flow_rate_h: 850
  flow_rate_v: 550
- flow_rate_h: 850
  flow_rate_v: 400
- flow_rate_h: 700
  flow_rate_v: 850
- flow_rate_h: 550
  flow_rate_v: 850
- flow_rate_h: 400
  flow_rate_v: 850
- flow_rate_h: 1000
  flow_rate_v: 850
- flow_rate_h: 1000
  flow_rate_v: 700
- flow_rate_h: 1000
  flow_rate_v: 550
- flow_rate_h: 1000
  flow_rate_v: 400
- flow_rate_h: 850
  flow_rate_v: 1000
- flow_rate_h: 700
  flow_rate_v: 1000
- flow_rate_h: 550
  flow_rate_v: 1000
- flow_rate_h: 400
  flow_rate_v: 1000
```
the command is:
```
python intersection.py results/fourway_1x1_penetration0.5
```
the log is 
```
i 104 | ii 255 | n_veh_step_mean 14.1 | n_veh_step_sum 2.82e+04 | n_veh_unique 387
2022-10-29 21:17:27,083 WARNING [worker.py:1829](http://worker.py:1829) -- A worker died or was killed while executing a task by an unexpected system error. To troubleshoot the problem, check the logs for the dead worker. RayTask ID: ffffffffffffffff8d9f376e21fe8973fcb0e4d701000000 Worker ID: 3fa7a262580beff71dedab84f2f6ab1a617716292ec00bb73de6dc8c Node ID: 9aedc44a625880aa7985a83bf5aa403f3d9601298409d51e53973e2c Worker IP address: 192.168.96.4 Worker port: 43775 Worker PID: 186329 Worker exit type: SYSTEM_ERROR Worker exit detail: Worker unexpectedly exits with a connection error code 2. End of file. There are some potential root causes. (1) The process is killed by SIGKILL by OOM killer due to high memory usage. (2) ray stop --force is called. (3) The worker is crashed unexpectedly due to SIGSEGV or other unexpected errors.
i 104 | ii  0 | policy_loss -2.01 | kl -5.98e-12 | entropy 0.211
i 104 | gd_time 119 | total_time 7.35e+04

i 105 | klcoef 0 | lr 0.001

Saved model /home/ubuntu/data/Jeffrey/mixed_autonomy_intersections/results_xlchan/fourway_1x1_penetration0.5/models/model-105.pth at step 105

Traceback (most recent call last):

  File "/home/ubuntu/data/Jeffrey/mixed_autonomy_intersections/intersection.py", line 313, in <module>

    c.run()

  File "/home/ubuntu/data/Jeffrey/mixed_autonomy_intersections/exp.py", line 357, in run

    c.train()

  File "/home/ubuntu/data/Jeffrey/mixed_autonomy_intersections/exp.py", line 289, in train

    rollouts = c.rollouts()

  File "/home/ubuntu/data/Jeffrey/mixed_autonomy_intersections/exp.py", line 174, in rollouts

    rollout_stats = flatten(ray.get([w.rollouts_single_process.remote() for w in c._rollout_workers]))

  File "/home/ubuntu/data/anacond3/envs/drl/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper

    return func(*args, **kwargs)

  File "/home/ubuntu/data/anacond3/envs/drl/lib/python3.8/site-packages/ray/_private/worker.py", line 2282, in get

    raise value

ray.exceptions.RayActorError: The actor died unexpectedly before finishing this task.

  class_name: GridExp

  actor_id: 8d9f376e21fe8973fcb0e4d701000000

  pid: 186329

  namespace: 7bd7b1ab-09a7-4e4d-ac05-d44f61be5dbd

  ip: 192.168.96.4

The actor is dead because its worker process has died. Worker exit type: SYSTEM_ERROR Worker exit detail: Worker unexpectedly exits with a connection error code 2. End of file. There are some potential root causes. (1) The process is killed by SIGKILL by OOM killer due to high memory usage. (2) ray stop --force is called. (3) The worker is crashed unexpectedly due to SIGSEGV or other unexpected errors.
```
My device has 48 CPUs. the version of ray is 2.0.1. Can you provide the detailed versions of python package?(Maybe it is not related to this issue.)
Is there any way to fix this?

**Comment by ZhongxiaYan** [comment]
Run it with less num_rollout_per_worker maybe?

**Comment by Jeffrey28** [comment]
It has been running for 105 steps taking 20 hours. I wonder why it was interrupted in the middle. Could you provide the detailed versions of python packages? Is my device configured enough?

**Comment by ZhongxiaYan** [comment]
It is an annoying known issue, probably an issue with Ray. The memory usage
increases during training and could crash after some number of training
steps. You can just continue training from where it crashed as the
checkpoint is saved. I couldn't find a better solution

**Comment by Jeffrey28** [comment]
Yeah, and it is hard to reproduced. So if I restart according to the above mentioned configuration and command, it will continue from the step 105. But the tensorboard log will not continue and the train_results.csv also will be changed. Ok, I will try again waiting for the other training to finish.
